services:

  php:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: notification-php
    tty: true
    working_dir: /var/www
    volumes:
      - ./docker/php-fpm/config/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./:/var/www
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - notification

  nginx:
    image: nginx:alpine
    container_name: notification-nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - notification

  postgres:
    image: postgres:18-alpine
    container_name: notification-postgres
    environment:
      PGPASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE}', '-U', '${DB_USERNAME}']
      interval: 5s
      retries: 5
      timeout: 5s
    networks:
      - notification

  redis:
    image: redis:alpine
    container_name: notification-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      retries: 5
      timeout: 5s
    networks:
      - notification

  kafka:
    image: apache/kafka:4.3.0
    container_name: notification-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
    healthcheck:
      test: ['CMD-SHELL', '/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 >/dev/null 2>&1']
      interval: 10s
      retries: 10
      timeout: 10s
      start_period: 15s
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - notification

volumes:
  postgres-data:
  kafka-data:

networks:
  notification:
    driver: bridge
